### ISSUE TITLE
Feature Request: Convenience Function to Construct Input Series

### ISSUE THREAD

**Issue by jvivian** [jnothman/UpSetPlot#41] opened 2018-08-28 13:41 UTC
Thanks for making this package given the lack of maintenance on `py-upset`. For me, the hardest part of using the package is turning my sets into the multi-Index Series that is the current input. It'd be convenient if there were an included function for constructing it, or, more ideally, if the input simply accepted sets directly.

Ideally: 
```python
a = set(['a', 'b', 'c', 'f'])
b = set(['a', 'b', 'd'])
c = set(['b', 'd', 'e', 'f'])

from upsetplot import plot
plot([a, b, c])
```

or 

```python
a = set(['a', 'b', 'c', 'f'])
b = set(['a', 'b', 'd'])
c = set(['b', 'd', 'e', 'f'])

from upsetplot import plot, upset_from_sets
upset = upset_from_sets([a, b, c])
plot(upset)
```

**Comment by jnothman** [comment] 2018-08-28 14:25
See also #23, #37

**Comment by jnothman** [comment] 2018-08-28 14:26
In fact, this is a duplicate of #23

**Closed** 2018-08-28 14:26 UTC

**Comment by jvivian** [comment] 2018-08-28 14:29
@jnothman — I have some downtime at the airport right now, I'd be happy to submit a pull request once I clean up the implementation.

**Comment by jnothman** [comment] 2018-08-28 14:36
You have an implementation? I just started working on one, though I should go to sleep instead. I was considering the name `import_dict_of_collections` to just return a usable input. But I look forward to your PR if you wish!

**Comment by jnothman** [comment] 2018-08-28 14:54
With apologies for pipping you at the post (silly of me to have suggested a PR and then to do it), but:
```py

def import_dict_of_collections(data):
    keys = sorted(data.keys())
    item_to_mask = defaultdict(lambda: [False] * len(keys))
    for i, k in enumerate(keys):
        collection = data[k]
        for item in collection:
            item_to_mask[item][i] = True
    items, index = zip(*item_to_mask.items())
    index = pd.DataFrame(list(index), columns=keys).set_index(keys).index
    return pd.Series(items, index=index)
```

is a basic implementation IMO. It would enjoy documentation, tests, and improvements to functionality.

**Comment by jvivian** [comment] 2018-08-28 15:17
@jnothman — Your function returned something a bit different than I expected — my implementation returns a `pd.Series` with the intersection counts as values:

```python
a = set(['a', 'b', 'c', 'f'])
b = set(['a', 'b', 'd'])
c = set(['a', 'b', 'd', 'e', 'f'])
d = set(['a', 'b', 'z'])

data = {'s1': a, 's2': b, 's3': c, 's4': d}

upset = upsetplot.data.from_sets(ds)
```
```
s1     s2     s3     s4   
True   True   True   True     2
                     False    0
              False  True     0
                     False    0
       False  True   True     0
                     False    1
              False  True     0
                     False    1
False  True   True   True     0
                     False    1
              False  True     0
                     False    0
       False  True   True     0
                     False    1
              False  True     1
                     False    0
dtype: int64
```

**Comment by jnothman** [comment] 2018-08-28 23:28
You're right. It was late and I was not quite thinking right. What I
produced should be a DataFrame, which the plotting system knows how to
aggregate... I'll have to think about it a bit more, but will check out
your PR

**Comment by jnothman** [comment] 2019-03-11 11:40
@jvivian. I hope you like the new data input supported in version 0.2.0 through `from_memberships`. (I'm considering making it possible to just specify `memberships` to `plot`, but if so that will be 0.3.0). Feedback very welcome!
