### ISSUE TITLE
TypeError: Argument 'obj' has incorrect type (expected list, got FrozenList)

### ISSUE THREAD

**Issue by jjc1** [jnothman/UpSetPlot#145] opened 2021-07-30 13:39 UTC
I tried to run the example at https://gist.github.com/eetuko/46bed58baa03e2dd348920322870c8b7 and the examples in the documentation (https://upsetplot.readthedocs.io/en/stable/) on 30 July 2021 on PyCharm and got the following errors every time:

Traceback (most recent call last):

  File "-----------site-packages\upsetplot\plotting.py", line 646, in plot
    return UpSet(data, **kwargs).plot(fig)
  File "------------\site-packages\upsetplot\plotting.py", line 600, in plot
    self.plot_matrix(matrix_ax)
  File "---------\site-packages\upsetplot\plotting.py", line 435, in plot_matrix
    idx = np.flatnonzero(data.index.to_frame()[data.index.names].values)
  File "----------------\site-packages\pandas\core\frame.py", line 3445, in __getitem__
    if com.is_bool_indexer(key):
  File "------------\site-packages\pandas\core\common.py", line 146, in is_bool_indexer
    return len(key) > 0 and lib.is_bool_list(key)
TypeError: Argument 'obj' has incorrect type (expected list, got FrozenList)

**Comment by jnothman** [comment] 2021-07-31 12:36
Please upgrade pandas to version 1.3.1. This was a known issue in Pandas 1.3.0.

Duplicate of #141

**Closed by jnothman** 2021-07-31 12:36 UTC
