### ISSUE TITLE
Highlighting specific interations

### ISSUE THREAD

**Issue by droricu** [jnothman/UpSetPlot#110] opened 2020-12-31 20:25 UTC
First, just wanted to say thanks for making and maintaining this library. It is super helpful!

My question: is there currently a way to highlight specific interactions (similar to the 'query' argument in pyupset)? I was able to highlight the specific bar by walking down the figure tree, but not the intersections. Here's the desired output:

![image](https://user-images.githubusercontent.com/42256032/103424782-3c460780-4b63-11eb-9939-9d02c0a0bf7b.png)

I tried seeing if this was asked before but couldn't find anything, so sorry if it has. Also, sorry if my question isn't phrased appropriately, I'm pretty new to this.

**Comment by jnothman** [comment] 2021-01-04 02:36
Yes, I've been trying to come up with a way to give you access to the matplotlib artists for a specified intersection, rather than making this specifically about colour... but maybe I'm trying too hard.

(I'm not happy with the overlap on that tick label text. Leaving enough space is a bigger and recurrent issue that deserves some investigation. I don't think matplotlib is giving me the flexibility I want for layout.)

**Comment by jnothman** [comment] 2021-07-31 15:27
Closing as duplicate of #46

**Comment by jnothman** [comment] 2021-08-01 23:06
Working on this in #152

**Closed** 2021-08-01 23:07 UTC
