### ISSUE TITLE
More control over ordering

### ISSUE THREAD

**Issue by kernco** [jnothman/UpSetPlot#108] opened 2020-10-12 20:21 UTC
Instead of just the two options for order_by, "cardinality" and "degree", there should be a third option "given" which just uses the order that the subsets are in when iterating over the data object.

The ordering of the categories could also use additional support for specifying an exact order that the user wants them to appear in. The behavior of sort_categories_by=None is not well explained in the documentation. It says it will "leave them in the provided order", but the subsets are what are provided, and the categories are inferred by contents of the subsets. So it isn't clear what the order will be. I have tried changing the order of the subsets given, but that doesn't seem to change the order of the categories in the plot.

**Comment by jnothman** [comment] 2020-10-13 12:30
Thanks for contributing!
"given" is a nice nomenclature. Is this otherwise a duplicate of #99?

**Closed** 2021-07-01 07:02 UTC
